# Generated by Django 3.1.6 on 2021-03-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('university_id', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
